Added card sections
maserekafelex/Portfolio-project pull request #2
Opened 2023-07-05 11:21 UTC by maserekafelex

I have create this project in html and css.
I have add images to make my project look good

2023-07-05 12:13 UTC, mckent05 requested changes
Hi @maserekafelex, 

# STATUS: CHANGES REQUIRED ♻️ ♻️ 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
![almost there](https://user-images.githubusercontent.com/73607512/207265056-d056ea78-77c5-4b66-802e-694a5ed4ecf3.gif)

## Highlights
- All linter checks are passing ✔️ ✔️ 
- Your PR is professional 👍 👍 
- Good job adding your work section and about me section to your portfolio 😄 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
**OPTIONAL** - Please consider making your PR description a little more descriptive and include some more details about changes you made in this PR, this would help your PR and repo look more professional 😄 
Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-05 23:30 UTC, Munsa1 requested changes
Hi @maserekafelex, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights
Good design :heavy_check_mark: 
Correct GitHub Flow :heavy_check_mark: 
Descriptive ReadMe File :heavy_check_mark: 

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
### Important 🔴 
- [ ] Going forward kindly Capitalize your commit messages by capitalizing the first letter of the first word of your commits for a more professional approach toward your work documentation.


_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-05 23:30 UTC, Munsa1 commented on Index.html
> +        <section id="cards">
- [ ] As requested by the previous reviewer kindly use `grid` to on the main container of the `projects` section to display elements

2023-07-05 23:30 UTC, Munsa1 commented on Index.html
> +                        </div>
- [ ] As requested by the previous reviewer kindly fix your design so as to match the given Figma design template

Your design
![image](https://github.com/maserekafelex/Portfolio-project/assets/81932478/f278bd90-0f27-4d39-b613-b3c3658a5adf)

Given design
![image](https://github.com/maserekafelex/Portfolio-project/assets/81932478/448ee0eb-7537-4c0e-8bdb-a2077212e361)

- The color of the `languages` text should match that of the given design
- The text should be aligned to the center vertically as is in the given design
![image](https://github.com/maserekafelex/Portfolio-project/assets/81932478/dbdc1573-74d8-48ca-b945-df7250faeaac)
- The grey background color for each of these languages should match that of the given design.
- The `Frameworks` and `Skills` should be styled as is in the given design, including the color of the underline and spacing
Given design
![image](https://github.com/maserekafelex/Portfolio-project/assets/81932478/fb12f45e-13b8-4dd9-90e0-cba33c04b0b3)

Your design
![image](https://github.com/maserekafelex/Portfolio-project/assets/81932478/5a8ba2df-5dda-4a28-af02-184e32f15e21)


#### Note that padding and spacing should be given special attention so as to closely match the given design 🔴

2023-07-07 07:11 UTC, abdulhamiid requested changes
# Status: Required Changes :recycle:
Hi @maserekafelex 👋, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, I really appreciate the effort you put in! but there are still some which haven't been addressed yet.

![almost-there](https://user-images.githubusercontent.com/57562869/143511358-9cde7daf-4ad0-4db2-8f15-18b54288ff91.gif)

## Highlights 🌟

- ✔️ Use Flexbox to place elements on the page.
- ✔️ Use CSS Grid to place elements on the page.
- ✔️ Parse a Figma design to create a UI.

## Required Changes ♻️
_Please kindly check the comments under the review._

## Optional suggestions 🤷‍♂️
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers, and Happy coding!👏👏👏

## Important Notes 📝
- Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
- Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-07 07:11 UTC, abdulhamiid commented on Index.html
> +                            </ul>
Figma
![tempsnip](https://github.com/maserekafelex/Portfolio-project/assets/78251927/8962bec4-cf23-48f2-89f6-e720f1664e84)

Your design
![tempsnip2](https://github.com/maserekafelex/Portfolio-project/assets/78251927/8a07f8ee-4efa-43b7-a176-a55971c3f7fa)

As requested by the previous reviewer and according to the [project requirements](https://github.com/microverseinc/curriculum-html-css/blob/main/portfolio/2_mobile.md), it is important that we stick to the design as much as possible (e.g., font, colors, images, text, margins) using [the templates in Figma](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=0%3A1).

- [ ] Kindly adjust the alignments of the elements in your design similar to the given template ☺, 

- [ ] Let's follow project core requirements for professional projects, and if we practice from our learning experience it will be easier in the future at the industry level.

2023-07-07 20:42 UTC, franclobo approved these changes
Hi @maserekafelex, 

# STATUS: APPROVED 😃 

![git-merge](https://github.com/maserekafelex/Portfolio-project/assets/58642949/0f4b5bb2-ea99-4060-ae44-bd4db1ec8e9c)

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights

- No linter errors ✔️ 
- Descriptive PR ✔️ 
- Correct Github flow ✔️ 
- Use Flexbox and Grid ✔️ 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-10 08:07 UTC, merged